name: Cleanup old chats
on:
  schedule:
    - cron: "0 3 * * *" # каждый день в 03:00 UTC
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx ts-node scripts/deleteOldChats.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
